### ISSUE TITLE
BUNZL - VW_BZL_Pedido_Pag

### ISSUE THREAD

**Issue by rosanaprignolato** [patricknaka/Nova#438]
Fábio, 

Conferindo os dados extraídos desta view, fiquei com a seguinte dúvida: Estou analisando o Pedido "50233328" e pela sessão de Pedidos Integrados ele tem 2 sequenciais. Quando eu detalho o sequencial 1, consigo pegar todas as informações existentes na view referente ao pagamento. Já o sequencial 2 não mostra nada nas telas do LN referente à pagamento, entretanto a view está retornando valores.

Sequencial 1:

![image](https://cloud.githubusercontent.com/assets/7606062/7796997/6d471658-02bc-11e5-914d-fabaadc2b14f.png)

Sequencial 2: 

![image](https://cloud.githubusercontent.com/assets/7606062/7797003/8ae4ce9e-02bc-11e5-8a04-4f0ac595f9e3.png)

Retorno dos dados pela view:

![image](https://cloud.githubusercontent.com/assets/7606062/7797015/c2845d06-02bc-11e5-93fb-ede56332aa1f.png)
 
Você poderia analisar?

Obrigada
Rosana

**Comment by fabioInfor** [comment]
Rosana,

A sequencia 2 não mostra nenhuma linha de pagamento, repare que para o pedido com sequencia 2 a entrega é 5023332802. O problema é que para este numero de entrega temos dois pedidos (050233329, 50233328) relacionados, isto não deveria acontecer, deve ser algum teste, mas se quiser podemos incluir o número do pedido para evitar enganos. Veja abaixo pedidos com este numero de entrega:

![image](https://cloud.githubusercontent.com/assets/7606647/7800200/54b053bc-02e8-11e5-98a2-713962a7c619.png)


![image](https://cloud.githubusercontent.com/assets/7606647/7800206/66b8f15e-02e8-11e5-96bf-33ce85ee5c34.png)

**Comment by rosanaprignolato** [comment]
Fabio, neste caso eu acho mais prudente inserirmos essa informação, mesmo sabendo que isso não deve ocorrer no ambiente de produção.

Você poderia providenciar a inclusão?

Obrigada
Rosana
