### ISSUE TITLE
VW_NK_FAT_FATURAMENTO

### ISSUE THREAD

**Issue by marcusmsv** [patricknaka/Nova#441]
Fabio,

Conforme verificamos, o CD_TIPO_ENTREGA da view de faturamento, esta retornando valor '0' sem ter um domínio correspondente na view VW_NK_DOM_TIPO_ENTREGA.

Poderia verificar com os técnicos da Infor, se houve teste manual no registro dos dados desta tabela, ou se haverá o domínio '0' no cadastro?

Obrigado.

**Comment by fabioInfor** [comment]
Marcus,

O dados que temos hoje na "tabela muro" de pedidos foram criados manualmente e o código do tipo de entrega foi criado com valor zero para as linhas de "customização". Conversei com o Rodrigo do front Nike e ele não soube dizer se em produção ficará assim mesmo ou terá o mesmo código que a linha do produto. Ele espera ainda esta semana fazer uma carga com dados reais do front dai poderemos verificar.

Conforme os resultados do front (se for mesmo zero para estas linhas) precisaremos talvez considerar o valor zero como um tipo "genérico" para as linhas de customização.

**Comment by patricknaka** [comment]
concluido
