### ISSUE TITLE
VW_NK_LOJA_ENT_SAI - Inclusão Tipo Docto. Fiscal

### ISSUE THREAD

**Issue by rodrigocarvm** [patricknaka/Nova#448]
Humberto,

Preciso que seja enviado os campos: CFOP e Tipo Docto Fiscal na view VW_NK_LOJA_ENT_SAI. 

São os mesmos campos que inserimos na LOJA_NF.

**Comment by rodrigocarvm** [comment]
Humberto, não consegui localizar os campos CFOP e Tipo Docto. Fiscal. eles foram incluídos?

**Comment by hkasai** [comment]
Rodrigo, os campos foram incluídos agora.
