### ISSUE TITLE
VW_NK_LOJA_ENT_SAI - Cód Romaneio Produto

### ISSUE THREAD

**Issue by rodrigocarvm** [patricknaka/Nova#450]
Humberto,

O campo ROMANEIO_PRODUTO das views VW_NK_LOJA_ENT_SAI E ENT_SAI_PRODUTO estão com o formato de data errado.

Ex: "11039110-AUG-15 "

O correto seria o formato numérico para chegar a chave do romaneio

**Comment by hkasai** [comment]
Rodrigo,

As querys foram corrigidas e atualizadas no Github.

Qualquer problema, me avise.

Grato, Humberto.

**Comment by rodrigocarvm** [comment]
Humberto,

LOJA_ENT_SAI - Todos os romaneios estão negativos.
LOJA_ENT_SAI_PRODUTO - ainda está com formato de data.

**Comment by hkasai** [comment]
Rodrigo,

Executei as querys e não aparecem com estes erros no SQL Developer. 
Vemos isto na segunda de manhã.
