### ISSUE TITLE
VW_NK_LOJA_NF_ITEM - CD_TRIBUTO_ORIGEM

### ISSUE THREAD

**Issue by rodrigocarvm** [patricknaka/Nova#451]
Humberto,

O campo CD_TRIBUTO_ORIGEM precisa se codificado com os valores abaixo:

0 - NACIONAL, EXCETO AS INDICADAS NOS CÓDIGOS 3 A 5                                                                                                        
1 - ESTRANGEIRA - IMPORTAÇÃO DIRETA, EXCETO A INDICADA NO CÓDIGO 6                                                                                         
2 - ESTRANGEIRA - ADQUIRIDA NO MERCADO INTERNO, EXCETO A INDICADA NO CÓDIGO 7                                                                             
3 - NACIONAL, MERCADORIA OU BEM COM CONTEÚDO DE IMPORTAÇÃO SUPERIOR A 40%                                                                                  
4 - NACIONAL, CUJA PRODUÇÃO TENHA SIDO FEITA EM CONFORMIDADE COM OS PROCESSOS PRODUTIVOS BÁSICOS DE QUE TRATAM AS LEGISLAÇÕES CITADAS NOS AJUSTES          
5 - NACIONAL, MERCADORIA OU BEM COM CONTEÚDO DE IMPORTAÇÃO INFERIOR OU IGUAL A 40%                                                                         
6 - ESTRANGEIRA - IMPORTAÇÃO DIRETA, SEM SIMILAR NACIONAL, CONSTANTE EM LISTA DA CAMEX                                                                     
7 - ESTRANGEIRA - ADQUIRIDA NO MERCADO INTERNO, SEM SIMILAR NACIONAL, CONSTANTE EM LISTA DA CAMEX

**Comment by hkasai** [comment]
Rodrigo,

No Ln temos duas opções que conflitam com o Código 3, da Nike. Temos a opção "5" de Nac. conteúdo import. > 40 e <= 70 e a opção "10" de Nac. conteúdo import. > 70.

Qual utilizamos ?
