### ISSUE TITLE
VW_NK_LOJA_VENDA_PGTO_PARCELAS - NR_AUTORIZACAO_CARTAO 

### ISSUE THREAD

**Issue by rodrigocarvm** [patricknaka/Nova#452]
Humberto,

O campo NR_AUTORIZACAO_CARTAO está vindo com números negativos.

**Comment by hkasai** [comment]
Rodrigo,

Os dados vieram com valor negativo do Front. No Barateiro não encontrei nenhum caso deste tipo em Produção.

Quer que eu trate e deixe o valor absoluto ?

**Comment by hkasai** [comment]
Rodrigo, alterei a query para mostrar o valor absoluto do campo.
