### ISSUE TITLE
VW_NK_LOJA_NF

### ISSUE THREAD

**Issue by rodrigocarvm** [patricknaka/Nova#455]
Humberto,

A View Loja_NF não está trazendo o campos de entrega/endereço para as notas de recebimento.

Será necessário pegar o cnpj que está recebendo (Nike) e retornar o endereço de faturamento dela.

Obs.: Não é necessário aplicar a regra de "Endereço de Entrega <> Endereço de Fatura"

**Comment by hkasai** [comment]
Rodrigo,

Alteração realizada e atualizada no Git. 

Qualquer problema, me avise.

Grato, Humberto.
