### ISSUE TITLE
STG_FAT_FATURAMENTO

### ISSUE THREAD

**Issue by rosanaprignolato** [patricknaka/Nova#464]
Humberto,

Problema 1:

Executando a view STG_FAT_FATURAMENTO no ambiente de homologação recebo 6 registros iguais para a Referência Fiscal “F20030688”. Existem outras referências que também estão trazendo vários registros. Você poderia analisar a view para identificar o motivo dessa duplicidade de informações?

![image](https://cloud.githubusercontent.com/assets/7606062/11538668/1f246d4c-990a-11e5-8199-ec933b531f1d.png)

Problema 2:
Analisando os dados identifiquei que existem registros no LN que não estão sendo lidos, porém os filtros existentes estão de acordo com os filtros que a view utiliza. Cito como exemplo a Referência Fiscal "F20030560" que no LN está com o Status Fatura = "Lançada" e o Status NFE = "Processada', mas a view não está trazendo nenhuma informação.

Execução View:

![image](https://cloud.githubusercontent.com/assets/7606062/11538493/6d1ce228-9909-11e5-9287-7d4a5581362c.png)
 
Telas LN:

![image](https://cloud.githubusercontent.com/assets/7606062/11538602/dceb0b98-9909-11e5-8cd1-b308a60979d7.png)

**Comment by hkasai** [comment]
Rosana,

Para o primeiro caso, houve divisão da entrega nas tabelas "cisli245" e "tdsls401", duplicando os registros.

Corrigi a query para buscar somente um registro para cada ordem e linha do pedido, em ambas as tabelas, desconsiderando as entregas parciais.

A query foi corrigida no GIT.

Grato, Humberto.

**Comment by hkasai** [comment]
![image](https://cloud.githubusercontent.com/assets/8986936/11685880/8bd2bed6-9e63-11e5-9be4-fe9a7dfd9e30.png)

**Comment by hkasai** [comment]
Rosana,

Quanto ao problema 2, a nota é de Saldão, que não possui pedido site e não é considerado pela query.

Algumas notas, que não são de Saldão, S00006, não aparecem na query, pois foram criadas sem pedido site, para testes no ambiente.

As notas de Troca agora aparecem, pois alteramos a query para o pagamento (znsls402) não ser obrigatório. As notas de Troca não tem pagamento (znsls402).

A query também não considera as notas de coleta (retorno mercadoria cliente).

Todas as notas, obrigatoriamente, tem que ter origem pelo site.

Qualquer dúvida, me avise.

Grato, Humberto.

**Comment by rosanaprignolato** [comment]
Humberto, 

PROBLEMA 1: RESOLVIDO

PROBLEMA 2:

Conforme conversamos, ainda estou encontrando divergências nos dados. Te mandei a planilha por e-mail reportando alguns casos que aparentemente estão dentro das condições de extração, porém os dados não são extraídos pela view. Você poderia analisar novamente?

Outro problema que precisamos resolver é a performance desta view.

Obrigada

**Comment by marcos-matias** [comment]
Rosana, boa tarde.
Sobre o problema 2: segui as referencias que você enviou ao Humberto via email. 
A referencia 120000374 possui o item da OV diferente do item do pedido - site. Isso é problema na base de homologação. 



As demais referencias marcadas em vermelho sairam na query. Rodei com filtro pela referencia e sem filtro, para me certificar. Você pode testar novamente?

Sds,

Matias

**Comment by rosanaprignolato** [comment]
Ok Matias, executei a view e todas as referências agora aparecem.
