### ISSUE TITLE
VW_PEV_CAB - Entrega com Devolução/Troca

### ISSUE THREAD

**Issue by rosanaprignolato** [patricknaka/Nova#465]
Humberto,

Carregando os dados gerados por essa view, identificamos um caso em que o mesmo NR_ENTREGA possui 2 NR_ENTREGA_CANCELADO, conforme demonstrado abaixo:

![image](https://cloud.githubusercontent.com/assets/7606062/11504657/8e3be6f2-982d-11e5-870f-ef513036ef1b.png)

Pela tela do LN podemos ver que se trata de 2 itens distintos. Isso está correto ?

![image](https://cloud.githubusercontent.com/assets/7606062/11504757/fcf8de9c-982d-11e5-81c8-cfd24c906f22.png)

**Comment by hkasai** [comment]
Rosana,

Analisando o pedido, verifiquei que o mesmo é de Venda (LJ), portanto, não tem pedido/entrega cancelados. Os campos estão errôneos, pode desconsiderar.

Qualquer dúvida, me avise.

Grato, Humberto.

**Comment by hkasai** [comment]
![image](https://cloud.githubusercontent.com/assets/8986936/11700682/6b629078-9eb2-11e5-8d77-e6354dc2d098.png)

**Comment by hkasai** [comment]
Rosana, 

Reorganizei os JOINs da query. Favor atualizar sua query com a do GIT.

Grato, Humberto.

**Comment by rosanaprignolato** [comment]
Humberto, 

Atualizei a query, porém a mesma precisa ter a sua performance revista. Está demorando muito para trazer as informações.

**Comment by hkasai** [comment]
Rosana,

Fiz algumas alterações e o tempo melhorou muito. Poderia validar novamente ?

**Comment by rosanaprignolato** [comment]
Humberto, 

A view continua com o seu tempo de processamento ruim. De acordo com o que conversamos, acredito que seja por conta do campo DT_ULT_ATUALIZACAO, o qual contém a seguinte instrução:

CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(greatest(tdsls400.t$rcd_utc, ulttrc.dtoc), 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
         AT time zone 'America/Sao_Paulo') AS DATE) DT_ULT_ATUALIZACAO

Seria possível você dar uma olhada nisso?

**Comment by hkasai** [comment]
Rosana,

Conforme alterações feitas pelo Ronaldo, a query teve seu tempo de processamento otimizado.

**Comment by rosanaprignolato** [comment]
Ok Humberto. Agora a query ficou mais rápida de ser executada
