### ISSUE TITLE
VW_PEV_DET - Registros Duplicados

### ISSUE THREAD

**Issue by rosanaprignolato** [patricknaka/Nova#466]
Humberto,

Identifiquei os problemas reportados abaixo:

Problema 1: NR_ORDEM = V20063462

A view está trazendo os dados duplicados para o item 1933:

![image](https://cloud.githubusercontent.com/assets/7606062/11506020/5e773514-9834-11e5-99c5-2bcd687db3a7.png)

Porém no LN, para o item 1933 só temos 6 quantidades:

![image](https://cloud.githubusercontent.com/assets/7606062/11505942/f9a01624-9833-11e5-955c-339d86f08004.png)

===============================================================================

Problema 2: NR_ORDEM = V50000183

A view está trazendo os dados duplicados para o item 410524:

![image](https://cloud.githubusercontent.com/assets/7606062/11506219/6fe6762e-9835-11e5-86dd-c61758713dcf.png)

Porém no LN, para o item 410524 só temos 2 quantidades:

![image](https://cloud.githubusercontent.com/assets/7606062/11506261/afb6c89e-9835-11e5-8ba3-b340f5d7f0f8.png)

===============================================================================

Problema 3: NR_ORDEM = V50000207

A view está trazendo os dados duplicados para o item 452075:

![image](https://cloud.githubusercontent.com/assets/7606062/11506346/37089d18-9836-11e5-8590-972562534422.png)

Porém no LN, para o item 452075 só temos 2 quantidades:

![image](https://cloud.githubusercontent.com/assets/7606062/11506329/21faade4-9836-11e5-9f66-f841b2b407c5.png)

O mesmo problema estamos encontrando para as ordens: V50000221, V50000225, V50000228, V50000240, V70000003 e V70000040

Você poderia analisar o problema?

**Comment by hkasai** [comment]
Rosana,

O problema de duplicidade acontece quando há entregas parciais. Nestes casos, as tabelas "tdsls401" e "cisli245" possuem sequencias para cada ordem/posição.
Já alterei a query reorganizando os JOINs e agora preciso agrupar os registros destas tabelas, mas continuo amanhã cedo.
Também já corrigi o problema dos pedidos de troca, que não tem registro de pagamento, "znsls402".

Grato, Humberto.

**Comment by hkasai** [comment]
Rosana,

A query foi corrigida e atualizada no GIT.

Grato, Humberto.
