### ISSUE TITLE
VW_PEV_CAB x VW_PEV_DET 

### ISSUE THREAD

**Issue by rosanaprignolato** [patricknaka/Nova#467]
Humberto,

Existem registros na PEV_CAB que não são lidos pela PEV_DET. Abaixo segue a relação de algumas ordens que eu identifiquei:

![image](https://cloud.githubusercontent.com/assets/7606062/11507176/f938034e-9839-11e5-9322-49d85b82872b.png)

Você poderia verificar o motivo?

**Comment by hkasai** [comment]
Rosana,

Executei as querys para estas ordens e todas apareceram, poderia verificar se há mais algum caso ?

Grato, Humberto.

**Comment by rosanaprignolato** [comment]
Ok Humberto. Pelo que validei agora está ok.
