### ISSUE TITLE
VW_PEV_CLIENTE - Registros Duplicados

### ISSUE THREAD

**Issue by rosanaprignolato** [patricknaka/Nova#468]
Humberto,

Essa view retornou 2 situações estranhas e precisamos identificar com você.

1) Entrega 4218704401
Para essa entrega temos 2 pedidos distintos: 042187254 e 042187255, conforme imagem. Isso está correto?

![image](https://cloud.githubusercontent.com/assets/7606062/11529147/47e6f7fa-98d2-11e5-9dbe-c3bd8f158bf3.png)

2) Entrega 5023424301
Para essa entrega, temos um registro com o DS_COMPLEMENTO_ENTREGA vazio e outro preenchido, conforme imagem:

![image](https://cloud.githubusercontent.com/assets/7606062/11529597/3eff6f0c-98d5-11e5-8a07-06860812c6c6.png)

Você poderia verificar?

**Comment by hkasai** [comment]
Rosana,

De acordo com a consultora Infor, estes pedidos foram copiados de forma errônea. Para cada pedido, há um número de entrega distinto.

Os pedidos foram gerados pelo Miller, do Back End, conforme print.

![image](https://cloud.githubusercontent.com/assets/8986936/11782298/635c57f8-a257-11e5-8cd9-8b65491c4c59.png)

**Comment by marcusmsv** [comment]
Humberto,

Conforme alinhamento da Equipe no dia 10/12, para casos como esses, caso sejam abertos para analise, deverão ser o ultimo da fila de prioridades, por se tratar de registros duplicados!

**Comment by rosanaprignolato** [comment]
Ok Humberto, obrigada!
