### ISSUE TITLE
VW_NFR_RASCUNHO_CAB - Campo DT_ULT_ATUALIZACAO

### ISSUE THREAD

**Issue by rosanaprignolato** [patricknaka/Nova#469]
Humberto,

Nesta view o campo DT_ULT_ATUALIZACAO está sendo gerado através da seguinte instrução:

  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(max(ttdpur451201.t$trdt), 
    'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT') 
    AT time zone 'America/Sao_Paulo') AS DATE) 
    from baandb.ttdpur451201 where ttdpur451201.t$orno=tdpur400.t$orno)

Entretanto, na view VW_NFR_RASCUNHO_DET este mesmo campo está sendo gerado pela instrução:

	CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(
		GREATEST(brnfe941.t$rcd_utc, tdpur401.t$rcd_utc, tdpur400.t$rcd_utc),
		'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
		AT time zone 'America/Sao_Paulo') AS DATE) DT_ATUALIZACAO	

Não teríamos que fazer o mesmo esquema feito na DET para a CAB também? Se ficar como está, acredito que a data de atualização correta não será refletida na CAB.

**Comment by hkasai** [comment]
Rosana,

Alterei a query "VW_NFR_RASCUNHO_DET" para trazer a mesma data da "CAB", ou seja, do histórico da linha da OV, "tdpur451". 

Também reorganizei os JOINs, tirando da cláusula "WHERE".

Grato, Humberto.

**Comment by rosanaprignolato** [comment]
Humberto, 

Conforme conversamos, você alterou ao contrário do que foi solicitado.

Precisamos que na "VW_NFR_RASCUNHO_CAB" a data da última atualização siga o mesmo critério definido na "VW_NFR_RASCUNHO_DET". 

![image](https://cloud.githubusercontent.com/assets/7606062/11814312/2e347386-a32d-11e5-8600-0f0460211bdb.png)

**Comment by hkasai** [comment]
Rosana,

As querys foram corrigidas e atualizadas no Git. Pode validar.

Grato, Humberto.

**Comment by rosanaprignolato** [comment]
Ok Humberto, as querys já foram substituídas.
