### ISSUE TITLE
VW_NFR_ULTIMO_RECEBIMENTO

### ISSUE THREAD

**Issue by rosanaprignolato** [patricknaka/Nova#470]
Humberto,

Conferindo os dados extraídos por essa view, identifiquei que alguns registros existem na tela do LN, porém não foram lidos pela view. Seria possível você verificar o motivo? 

Peguei as informações com a Data de Transação 13/11/2015, na seção whina1512m000 (Transações de Recebimento de Inventário) e os itens que não apareceram na view foram: 100012, 1743126, 1866349 e 1876067.

**Comment by hkasai** [comment]
Rosana,

Analisei os 4 casos e encontrei o seguinte: 

Para os itens 100012, 1743126 e 1876067, a query traz a última data de recebimento, que nestes casos, não é 13/11/2015, há datas posteriores.

Para o item 1866349, o último recebimento é na verdade um retorno de mercadoria do cliente, uma ordem de venda de devolução. Neste caso, tive que fazer uma alteração na query para considerá-lo. A query foi atualizada no GIT.

Seguem as evidências da análise, qualquer dúvida, me procure.

![image](https://cloud.githubusercontent.com/assets/8986936/11853078/10613348-a423-11e5-81af-87bddf1d3800.png)

![image](https://cloud.githubusercontent.com/assets/8986936/11853122/3fd0828c-a423-11e5-9d4b-8880082623c3.png)

![image](https://cloud.githubusercontent.com/assets/8986936/11853143/5e14ec4c-a423-11e5-8640-5571e130bebd.png)

![image](https://cloud.githubusercontent.com/assets/8986936/11853156/6fab3c04-a423-11e5-8a50-000e1fa38236.png)

![image](https://cloud.githubusercontent.com/assets/8986936/11853171/80dcc01a-a423-11e5-9026-72fd2ec921a2.png)

**Comment by rosanaprignolato** [comment]
Ok Humerto, 

Já atualizei a view no servidor e constatei que o item 1876067 agora está sendo extraído.
