### ISSUE TITLE
VW_DEV_DEVOLUCAO - Campo NR_REFERENCIA_FISCAL_FATURA

### ISSUE THREAD

**Issue by rosanaprignolato** [patricknaka/Nova#471]
Humberto,

Conferindo os dados extraídos pela view, me deparei com a seguinte situação:

Temos a NR_REFERENCIA_FISCAL_DEVOLUCAO = "R60000565", que segundo o detalhamento pelas telas do LN, chego em uma NR_REFERENCIA_FISCAL_FATURA = "F20027402", conforme imagem abaixo:

![image](https://cloud.githubusercontent.com/assets/7606062/11635365/674fa766-9cfd-11e5-8cf1-343b46b537ec.png)

A view está retornando no campo NR_REFERENCIA_FISCAL_FATURA a informação "F20027401". 

![image](https://cloud.githubusercontent.com/assets/7606062/11635438/f24e6884-9cfd-11e5-8cd9-888d7210688d.png)

Você poderia verificar o que está errado? A conferência que eu fiz no LN foi seguindo uma orientação que o Fábio havia me passado.

O mesmo está acontecendo em outros registros.

**Comment by patricknaka** [comment]
Humberto acho que esse caso vai ser necessário replicar a query de devolução que fizemos para a Ehbu

**Comment by hkasai** [comment]
Rosana,

A query foi alterada e atualizada no GIT. 

Qualquer problema, nos avise.

Grato, Humberto.

**Comment by rosanaprignolato** [comment]
Matias,

Conforme conversamos hoje durante o expediente, será necessário rever a view de devolução, pois aparentemente a mesma não está considerando a sequência do item para trazer alguns dados (NR_NF_FATURA, NR_SERIE_NF_FATURA, etc)

Fico no aguardo da correção para fazer uma nova validação.

**Comment by marcos-matias** [comment]
Rosana,

Havia um problema na base de dados. Os dois itens do pedido 000002179 seq 2 estavam com a mesma sequencia da entrega 5023379402 (ambos os itens estava com a sequencia 1). Não consegui achar mais casos, mas como essa cia é de homologação...

Sds,

Matias

**Comment by rosanaprignolato** [comment]
Ok Matias, já substitui a query e agora esses dados estão ok.

Peguei um outro probleminha e vou precisar da sua ajuda. Para essa mesma NR_REFERENCIA_FISCAL_DEVOLUCAO = "R60000565", os campos DT_PEDIDO, CD_STATUS e DT_STATUS não estão batendo com o LN. Acredito que seja porque não está buscando as informações do sequencial correto. Veja o que a view retorna:

![image](https://cloud.githubusercontent.com/assets/7606062/11913460/b36d04f2-a64b-11e5-956a-7f596a80a7f9.png)


O campo DT_PEDIDO referente à devolução tem a informação abaixo no LN, porém a view está retornando a informação do sequencial 1:

![image](https://cloud.githubusercontent.com/assets/7606062/11913439/29f44fe6-a64b-11e5-89f3-5402bed8178b.png)

Já para o CD_STATUS e DT_STATUS não está retornando nenhuma informação, porém no LN existem informações:

![image](https://cloud.githubusercontent.com/assets/7606062/11913477/09d52db0-a64c-11e5-8c57-d5a8633eb0d0.png)

Você poderia analisar?

Obrigada

**Comment by marcos-matias** [comment]
Campos DT_PEDIDOS, CD_STATUS e DT_STATUS corrigidos. Incluida a sequencia da NF.
Query atualizada no repositório.

**Comment by rosanaprignolato** [comment]
Matias,

O campo inserido NR_ITEM_NF deverá ser lidos das notas referentes ao campo NR_REFERENCIA_FISCAL, pois, segundo o Patrick, neste situação temos dados para todos os registros.

Você poderia alterar?

Obrigada

**Comment by marcos-matias** [comment]
Coluna NR_ITEM_NF alterada e posicionada ao lado da coluna NR_REFERENCIA_FISCAL. Query atualizada.

**Comment by rosanaprignolato** [comment]
Ok Matias, query atualizada.
