### ISSUE TITLE
VW_CAP_TITULO - Campo CD_BANCO_DESTINO

### ISSUE THREAD

**Issue by rosanaprignolato** [patricknaka/Nova#472]
Humberto,

PROBLEMA 1:

Pelo mapeamento de conferência feito anteriormente, esse campo é conferido pela tela do LN, quando detalhamos a linha apresentada em Programação de Pagamento, conforme imagem abaixo:

![image](https://cloud.githubusercontent.com/assets/7606062/11656482/add5d06c-9d9c-11e5-8b32-f1739a6ed3f5.png)

A transação PFA, titulo 998 apresentado na imagem, tem informação no campo Banco do Fornecedor, porém a view não está trazendo nenhuma informação:

![image](https://cloud.githubusercontent.com/assets/7606062/11656556/23491d0e-9d9d-11e5-9468-08bcace44b6e.png)
 

PROBLEMA 2:

Exportei todos os dados do LN para uma planilha considerando como data de corte o campo Data do documento maior ou igual à 13/11/2015 e executei a view utilizando o mesmo critério. Comparando os dados, apenas um título não veio na extração da view. O registro tem transação 300 e título 341:

![image](https://cloud.githubusercontent.com/assets/7606062/11656752/3c67e3dc-9d9e-11e5-827a-c2372acc7541.png)

**Comment by marcos-matias** [comment]
Rosana, 
As colunas CD_BANCO_DESTINO, NR_AGENCIA_DESTINO e NR_DIGITO_AGENCIA_DESTINO foram corrigidas e são carregadas com a mesma regra do LN.

As colunas NR_CONTA_CORRENTE_DESTINO e NR_DIG_ CONTA_CORRENTE_DESTINO também foram alteradas, sendo carregadas agora da tabela de contas por parceiro credor. Porém eu preciso validar essa regra, então segunda eu te retorno sobre isso...

Sds,

Matias

**Comment by rosanaprignolato** [comment]
Ok Matias! A query foi substituída e os campos agora estão OK. Caso não seja esse conceito, voltamos a nos falar.
