### ISSUE TITLE
VW_CAP_TITULO_PGTO - Campo DT_ULT_ATUALIZACAO

### ISSUE THREAD

**Issue by rosanaprignolato** [patricknaka/Nova#473]
Humberto,

Este campo deverá sempre considerar a data mais recente de qualquer atualização dos registros. Atualmente a view está trazendo as datas da seguinte maneira:

![image](https://cloud.githubusercontent.com/assets/7606062/11688478/0beb643c-9e74-11e5-8141-30ebe858dbc3.png)

Você poderia alterar?

**Comment by marcos-matias** [comment]
DT_ULT_ATUALIZACAO alterada para pegar o maior TIMESTAMP entre as tabelas de titulos e de agenda.
Query alterada no repositório.

**Comment by rosanaprignolato** [comment]
Ok Matias, agora a data está coerente.

Obrigada
