### ISSUE TITLE
VW_PEC_CAB - Novo campo

### ISSUE THREAD

**Issue by patricknaka** [patricknaka/Nova#474]
Rosana, precisamos incluir mais um campo na VW_PEC_CAB no final da query:

tdpur400.t$sorn DS_ORDEM_PN_FORNEC

Pode criar após a ultima coluna "DT_CRIACAO"

abs, PAtrick

**Comment by rosanaprignolato** [comment]
Patrick,

O campo já foi inserido e a base recarregada. Por favor, veja se ficou ok.

**Comment by patricknaka** [comment]
Está ok obrigado
