### ISSUE TITLE
VW_CAR_REMESSA_COBR_ELETR - Campos CD_COMANDO e CD_BANCO 

### ISSUE THREAD

**Issue by rosanaprignolato** [patricknaka/Nova#475]
Humberto, 

Você poderia me informar como faço para pegar essas informações na tela do LN?

Eu havia mapeado anteriormente que o campo CD_COMANDO era visto na tela do LN da seguinte maneira:

Entro na sessão tfcmg4501m000 (Lotes de Cobrança - Aconselhamento) e detalho a transação e título desejado. Na tela apresentada, seleciono  a aba "Diversos",  seção "Detalhes EBF" e pego a informação de "Código da Ocorrência" 

![image](https://cloud.githubusercontent.com/assets/7606062/11744487/f1c1f384-9ff7-11e5-9a01-974cc0f06e8b.png)

Acontece que para essa transação e Título (BR3 56) na tela do LN é apresentado 01 e a query está retornando 04. A sessão que usei trabalha com a tabela "tfcmg401" e a view com a tabela "tfcmg948". Eu não consegui achar esses campos na sessão que utiliza a mesma tabela da view.

**Comment by marcos-matias** [comment]
Rosana, por favor use o relatório tfcmgl404m00l - Imprimir documentos de saída EBF. O caminho é Finanças > Gestão de Banco > Cobranças > Cobrança Escritural > Imprimir documentos de saída EBF

**Comment by rosanaprignolato** [comment]
Ok Matias, já utilizei o relatório para conferência e agora os dados estão de acordo com o que vem da extração. Obrigada!
