### ISSUE TITLE
VW_CAR_TITULO - Campos DT_VENCIMENTO e DT_VENCIMENTO_ORIGINAL

### ISSUE THREAD

**Issue by rosanaprignolato** [patricknaka/Nova#477]
Humberto,

Estou validando o documento "309 400" através da sessão "tfacr2520m000" do LN. Esse documento apresenta uma data de vencimento em branco na tela do LN:

![image](https://cloud.githubusercontent.com/assets/7606062/11750174/24ed66fa-a019-11e5-8103-c2bd04aa2a0b.png)

Ao executar a view, ele apresenta uma data que não existe:

![image](https://cloud.githubusercontent.com/assets/7606062/11750237/77324520-a019-11e5-86f3-3705c34ea29e.png)

A view original tem um tratamento feito, entretanto, mesmo com esse tratamento os dados não são apresentados como no LN.

Você poderia analisar?

**Comment by marcos-matias** [comment]
Rosana, query corrigida e alterada no git.

**Comment by rosanaprignolato** [comment]
Ok Matias. A query foi substituida e os dados agora estão OK!
