### ISSUE TITLE
View VW_CAR_TITULO_REMESSA - Join duplicando registros

### ISSUE THREAD

**Issue by rosanaprignolato** [patricknaka/Nova#478]
Humberto,

Essa view tem um join que está duplicando as informações. Peguei como exemplo para conferência o documento "RB3 3879". Na tela do LN, eu vejo a seguinte informação:

![image](https://cloud.githubusercontent.com/assets/7606062/11789035/35cb85ce-a27b-11e5-815a-b0c8d92708aa.png)

Analisando pelo retorno dos dados da view, encontramos:

![image](https://cloud.githubusercontent.com/assets/7606062/11789127/a26e0814-a27b-11e5-938b-13f00ea2ab8b.png)

Pelo que eu pude notar, o problema está com esse join na view:

![image](https://cloud.githubusercontent.com/assets/7606062/11789163/d0b0ab50-a27b-11e5-93a1-1762c0c9000f.png)

Você poderia verificar?

**Comment by marcos-matias** [comment]
Rosana, o problema é que a busca por alguns campos não estava considerando a parcela. A query foi corrigida e atualizada no repositório.

**Comment by rosanaprignolato** [comment]
Ok Matias, o problema foi solucionado.
