### ISSUE TITLE
VW_NK_PEV_CAB - Ponto de Controle (CD_STATUS) - Ambiente de Produção

### ISSUE THREAD

**Issue by rosanaprignolato** [patricknaka/Nova#479]
Humberto,

Conforme conversamos, será necessário corrigir a view em questão para trazer o ponto de controle corretamente, baseado na sequência do pedido. 

Utilizamos como base de conferência o pedido "1219076".

**Comment by hkasai** [comment]
Rosana,

A query foi corrigida e atualizada no Git.

Os JOINs também foram reorganizados.

Grato, Humberto.

**Comment by rosanaprignolato** [comment]
Humberto, 

Já conferimos os novos dados extraídos por essa view e aparentemente estão ok. Fizemos uma inclusão do campo DT_PROMETIDA_RECALCULADA e alteramos a leitura do campo DT_LIMITE_EXPED. Por favor, atualize o seu controle.
