### ISSUE TITLE
VW_PEC_CAB - Ordens com valores e sem itens

### ISSUE THREAD

**Issue by rosanaprignolato** [patricknaka/Nova#480]
Humberto,

Fazendo a conferência dos registros entre a "VW_PEC_CAB" e "VW_PEC_DET" encontrei problemas com algumas ordens que possuem valores no cabeçalho, porém não tem itens. As ordens são:

![image](https://cloud.githubusercontent.com/assets/7606062/11811280/c49ecc3e-a31b-11e5-9828-5369153bfeef.png)

![image](https://cloud.githubusercontent.com/assets/7606062/11811261/acac976e-a31b-11e5-9cf1-376f3e3bf4e2.png)

Isso pode acontecer ou é sujeira na base de homologação?

**Comment by hkasai** [comment]
Rosana,

Pode desconsiderar estas ordens, é tudo teste de usuário.

**Comment by rosanaprignolato** [comment]
Ok Humberto, obrigada!
