### ISSUE TITLE
VW_PEV_DET - Ordens sem valor no CAB e com valores na DET

### ISSUE THREAD

**Issue by rosanaprignolato** [patricknaka/Nova#481]
Humberto, 

Conferindo os dados, encontrei a seguinte situação:

na PEV_CAB temos:

Entrega: 10000001201
Ordem Venda: V20054804
Valor: 0

na PEV_DET temos:

Entrega: 10000001201
Ordem Venda: V20054804
Valor: 69,20

Analisando pela tela do LN essa ordem está com o Status = CANCELADO, e apresenta o Valor da Ordem igual a zero, o que reflete na PV_CAB:

![image](https://cloud.githubusercontent.com/assets/7606062/11839772/9755dcba-a3d7-11e5-9181-22080019cabb.png)

Porém, quando fazemos o detalhamento da mesma, encontramos valores para o item e esse valor está entrando na carga dos detalhes:

![image](https://cloud.githubusercontent.com/assets/7606062/11839813/e4587fa4-a3d7-11e5-825c-1257653403e2.png)

Isso está correto?

**Comment by hkasai** [comment]
Rosana,

Corrigi a query para trazer o valor do pedido, quando o mesmo for cancelado.

**Comment by rosanaprignolato** [comment]
Ok Humberto!
