### ISSUE TITLE
VW_PEV_DET - Entregas que não encontro no LN

### ISSUE THREAD

**Issue by rosanaprignolato** [patricknaka/Nova#482]
Humberto,

A ordem (V20054804), na carga da PEV_DET apresenta 2 entregas:  10000001201 e 10000001202

![image](https://cloud.githubusercontent.com/assets/7606062/11839924/e5225148-a3d8-11e5-9c8c-1381ee3b201d.png)

Na tela do LN, essa ordem apresenta apenas uma entrega:

![image](https://cloud.githubusercontent.com/assets/7606062/11839975/50562f7a-a3d9-11e5-80b4-d9b7901f1d6e.png)

A entrega "10000001202" eu não encontro no LN:

![image](https://cloud.githubusercontent.com/assets/7606062/11840007/829126f2-a3d9-11e5-9cd4-7b2bc11c1488.png)

Você poderia verificar o que está acontecendo? Assim como essa ordem, outras também estão apresentando o mesmo comportamento.

**Comment by hkasai** [comment]
Rosana,

A entrega está na sequencia 2 do pedido, é referente a uma Troca/Devolução.

![image](https://cloud.githubusercontent.com/assets/8986936/11959240/670f8016-a8b3-11e5-9220-9d76bf8211d1.png)

![image](https://cloud.githubusercontent.com/assets/8986936/11959275/926faf2e-a8b3-11e5-9043-8166a85dd460.png)

**Comment by rosanaprignolato** [comment]
Ok Humberto, obrigada! Já consegui identificá-los.
