### ISSUE TITLE
VW_NFR_RASCUNHO_CAB - DT_EMISSAO_NF e DT_SAIDA_NF

### ISSUE THREAD

**Issue by rosanaprignolato** [patricknaka/Nova#483]
Humberto,

Existem algumas referências no LN que estão com a data da emissão em branco. Executando a query no ORACLE, recebemos a indicação de 01/01/4712. Como podemos resolver isso?

Cito como exemplo a Referência 'PR0002688'. A view retorna os dados abaixo:

![image](https://cloud.githubusercontent.com/assets/7606062/11844599/d1df9bc2-a3f6-11e5-9cee-b71a8952d128.png)

No LN, essa mesma referência apresenta os seguintes dados:

![image](https://cloud.githubusercontent.com/assets/7606062/11844653/0f5a001e-a3f7-11e5-9bc5-a3c1085e1bf5.png)

**Comment by hkasai** [comment]
Rosana,

Falei com o Jacques, da Infor, e o mesmo me informou que o Ln traz esta data como default.

Favor considerar como data nula.

**Comment by rosanaprignolato** [comment]
Ok Humberto, foi feito o tratamento necessário e a view foi atualizada no GIT. Agora os dados estão vindo como nulos em nossas tabelas.
