### ISSUE TITLE
VW_FAT_FATURAMENTO - Nf Marketplace

### ISSUE THREAD

**Issue by patricknaka** [patricknaka/Nova#484]
HUmberto, boa tarde.

Na view de Faturamento conseguimos desconsiderar as NF de Pós Consolidado e Marketplace pois não devemos efetuar a carga desses nos cubos do MIS.

Exemplo>

'F00000470' e '120000401'

abs, Patrick Nakazone

**Comment by hkasai** [comment]
Patrick,

A view foi alterada e atualizada no Git.

Seguem os campos e sessões referentes às alterações do Market Place e Faturas Pós_Consolidadas.

Market Place

![image](https://cloud.githubusercontent.com/assets/8986936/11943363/71d7ff8a-a824-11e5-849a-3c5dbf9483d8.png)

![image](https://cloud.githubusercontent.com/assets/8986936/11943370/82c190cc-a824-11e5-99dd-b5a05f306099.png)

![image](https://cloud.githubusercontent.com/assets/8986936/11943374/8fc2a4d2-a824-11e5-8144-663127c9d999.png)

Faturas Pós-Consolidadas - Parâmetros

![image](https://cloud.githubusercontent.com/assets/8986936/11943406/d2c6b14c-a824-11e5-8432-8311073ea537.png)

**Comment by patricknaka** [comment]
encerrado
