### ISSUE TITLE
VW_FAT_FATURAMENTO - NF fatura operação triangular

### ISSUE THREAD

**Issue by patricknaka** [patricknaka/Nova#485]
Humberto,

Estava verificando o processo de operação triangular e queria entender qual seria a diferença dos casos abaixo pois conforme o primeiro print esta retornando a NF de Remessa e Fatura (CD_TIPO_NF 15 e 16)  mas no segundo print só esta retornando o de remessa.

Pelo que vi os dois casos são de B2B - Cd_unidade_negocio =6

Print 1
![image](https://cloud.githubusercontent.com/assets/7632817/11913905/92c7315a-a65a-11e5-8d75-24611e629a2c.png)

Print 2
![image](https://cloud.githubusercontent.com/assets/7632817/11913885/f2052114-a659-11e5-9340-1d95ebda6715.png)

**Comment by hkasai** [comment]
Patrick,

O FAT_FATURAMENTO filtra o status da nota, e a nota 3202/1 está com o status Cancelado.

![image](https://cloud.githubusercontent.com/assets/8986936/11936035/78eed172-a7f2-11e5-9793-16779473ab03.png)

**Comment by hkasai** [comment]
Patrick,

A nota 3302/1 não aparece na FAT_FATURAMENTO, pois ela faz um JOIN com a "cisli941" com o campo de "Referência Fiscal Relativa", e o campo está não foi preenchido. Este campo é preenchido somente nas notas triangulares.

![image](https://cloud.githubusercontent.com/assets/8986936/11937327/cc732c6e-a7fa-11e5-9f2b-cf5c20f39f56.png)

**Comment by patricknaka** [comment]
Humberto poderia verificar com o Fiscal da Infor se os casos de Notas do B2B Pré consolidada não é um processo de NF Triangular?

**Comment by patricknaka** [comment]
Solicitação encerrada
