### ISSUE TITLE
VW_PEV_CLIENTE - Diferença entre View's

### ISSUE THREAD

**Issue by marcusmsv** [patricknaka/Nova#486]
Humberto,

Poderia verificar o caso do pedido abaixo, no qual não foi identificado na view de Pedido Cliente, e consta nas demais views de Pedido de Venda.

Pedido de Venda 5025688601

Pelo que validei, na view de Pedido Cliente, o tipo 14 - Retorno de mercadoria esta restringindo este caso.

Porem, nas demais views, ele utiliza o mesmo campo, tdsls400.t$fdty$l.

Qualquer problema, me avise!

Obrigado

**Comment by hkasai** [comment]
Marcos,

Encontrei uma inconsistência neste pedido, que faz ele não ser considerado na query.
O pedido gerou uma Ordem de Venda 'V50000157', como mostra a figura:
![image](https://cloud.githubusercontent.com/assets/8986936/11967228/39f917d8-a8e8-11e5-82c0-699e4ee751cb.png)

**Comment by marcusmsv** [comment]
Humberto,
Conforme validação, este pedido não consta na lista de teste da Infor.
