### ISSUE TITLE
VW_FAT_FATURAMENTO - Ref Fiscal F20030901

### ISSUE THREAD

**Issue by patricknaka** [patricknaka/Nova#487]
Humberto na View de Fat Faturamento não esta retornando a linha 50, poderia verificar?

![image](https://cloud.githubusercontent.com/assets/7632817/11940496/360e6444-a810-11e5-806c-fe677f98af16.png)

**Comment by hkasai** [comment]
Patrick, a ref. 'F2003608' não é impressa, pois é uma fatura triangular pré-consolidada, e ainda não possui as notas de remessa (referências relativas), como mostra a figura. A query possui um join que filtra este tipo de nota, sem referência relativa.

![image](https://cloud.githubusercontent.com/assets/8986936/11986506/7172e174-a9b7-11e5-8baa-893c49cddd56.png)

A ref.'F20030901', uma das remessas da ref."F2003608", possui somente 2 itens, conforme figura:

![image](https://cloud.githubusercontent.com/assets/8986936/11986527/c0a10d34-a9b7-11e5-8051-78892ed841ad.png)

A fatura possui estas remessas correspondentes: 

F20030632
F20030689
F20030901
F20030632
F20030689
F20030901
F20030647
F20031062

**Comment by patricknaka** [comment]
concluido
