### ISSUE TITLE
VW_SKU - Cod EAN

### ISSUE THREAD

**Issue by patricknaka** [patricknaka/Nova#488]
Humberto,

Poderia verificar porque alguns skus como os abaixo esta vindo com o Cod_EAN nulos:

CD_ITEM in ('5098','236404','298767','298769','302199','364986',
'410524','2247451','2247484','2256699','13424168','13424169','13425785') 

abs, Patrick Nakazone

**Comment by hkasai** [comment]
Patrick,

Para os itens que existem em Produção, os EANs estão preenchidos, provavelmente o cadastro da Homologação está desatualizado. Seria o caso de pedir para algum responsável pelo cadastro fazer a atualização.

**Comment by hkasai** [comment]
Marcus,

Conforme definido, a query "VW_SKU" foi corrigida para trazer o campo "tcibd001.t$cean" (Código EAN) caso o campo "tcibd001.t$ceat$l" (Código EAN Tributário) esteja em branco.

A query "VW_DOM_SKU_EAN" já trabalha com o campo "tcibd001.t$cean".

**Comment by patricknaka** [comment]
fechado
