### ISSUE TITLE
vw_trp_transporte - Inclusão de Colunas

### ISSUE THREAD

**Issue by patricknaka** [patricknaka/Nova#489]
Humberto precisamos incluir duas colunas na view de Transporte:
- NUME_ETIQUETA (znfmd630.t$etiq$c)
- Regiao (exemplo: SP - CAPITAL ) encontramos a query abaixo em outro relatório:
             ( select znfmd061.t$dzon$c
                 from baandb.tznfmd062201 znfmd062, 
                      baandb.tznfmd061201 znfmd061
                where znfmd062.t$cfrw$c = znfmd630.t$cfrw$c 
                  and znfmd062.t$cono$c = znfmd630.t$cono$c
                  and znfmd062.t$cepd$c <= tccom130.t$pstc
                  and znfmd062.t$cepa$c >= tccom130.t$pstc
                  and znfmd061.t$cfrw$c = znfmd062.t$cfrw$c
                  and znfmd061.t$cono$c = znfmd062.t$cono$c
                  and znfmd061.t$creg$c = znfmd062.t$creg$c
                  and rownum = 1 ) 
                                REGIAO,

abs, Patrick Nakazone

**Comment by hkasai** [comment]
Patrick,

Os campos foram incluídos na query.

**Comment by marcusmsv** [comment]
Alteração executada na camada staging do MIS.
