### ISSUE TITLE
VW_PEV_CLIENTE - Ordem de Venda

### ISSUE THREAD

**Issue by patricknaka** [patricknaka/Nova#490]
Humberto,

Na view VW_PEV_CLIENTE estamos utilizando o filtro "tdsls400.t$fdty$l != 14" mas pegamos alguns casos como o exemplo abaixo que na view esta retornando uma OV "V70000223" mas pela tela do LN esta retornando a OV "V70000034"

![image](https://cloud.githubusercontent.com/assets/7632817/12021052/d191907c-ad69-11e5-9eae-c713b898d797.png)

![image](https://cloud.githubusercontent.com/assets/7632817/12021086/1b57a64c-ad6a-11e5-88f0-bf9fe4fb9f9d.png)

Outro Exemplo:
![image](https://cloud.githubusercontent.com/assets/7632817/12021115/5c21c4be-ad6a-11e5-8c14-fe1ad8b59ac2.png)

![image](https://cloud.githubusercontent.com/assets/7632817/12021124/71e96c5c-ad6a-11e5-921d-6baddfcee827.png)

Poderia verificar?

**Comment by hkasai** [comment]
Patrick,

Conforme conversado, seguem as evidências do primeiro pedido, onde foram geradas duas OVs para a mesma entrega, um de venda e outro de devolução:

![image](https://cloud.githubusercontent.com/assets/8986936/12023795/50151b98-ad84-11e5-9770-f371ec8efc2f.png)

![image](https://cloud.githubusercontent.com/assets/8986936/12023800/5c4dfbb4-ad84-11e5-8f65-d78948847ad7.png)

**Comment by filipecomparini** [comment]
View ajustada.
