### ISSUE TITLE
VW_FAT_FATURAMENTO - Entrega com duas referencias fiscais

### ISSUE THREAD

**Issue by filipecomparini** [patricknaka/Nova#491]
Humberto,

Poderia me ajudar a entender se é uma sujeira na base? A entrega 5025687101 contêm a referencia fiscal 100001363 e F70000457.

Abs,
Filipe

**Comment by hkasai** [comment]
Filipe,

Conforme conversado, favor desconsiderar o pedido triangular, pois gerou uma remessa com valor preenchido.

![image](https://cloud.githubusercontent.com/assets/8986936/12024868/ef193cb4-ad8f-11e5-9364-a8e0fca590ef.png)
