### ISSUE TITLE
Relatório "RelatorioConciliacao" (201)

### ISSUE THREAD

**Issue by patricknaka** [patricknaka/Nova#492]
Matias, boa tarde.

No relatório Car Conciliação alguns registros não estão retornando a Unidade de Negocio conforme o print abaixo:

Consultado a referencia fiscal na nossa base o mesmo esta relacionado a um pedido

![image](https://cloud.githubusercontent.com/assets/7632817/12024714/1f7af0f2-ad8e-11e5-95df-589bbb639619.png)

poderia verificar?

**Comment by marcos-matias** [comment]
Patrick, havia um erro na hora de buscar o pedido referente à referência fiscal, a query considerava todas as referências como se fossem referências relativas (op. triangular).
Query atualizada no repositório.

Matias

**Comment by patricknaka** [comment]
Yuri, boa tarde.
Depois poderia atualizar o relatório em homologação?
abs, Patrick Nakazone

**Comment by YuriFialh0** [comment]
Relatório atualizado Patrick.

**Comment by patricknaka** [comment]
Concluido
