### ISSUE TITLE
VW_DOM_SKU_KIT - Código de sku com alfanumérico

### ISSUE THREAD

**Issue by filipecomparini** [patricknaka/Nova#493]
Humberto,

Hoje temos uma view que nos retorna os skus que compõem um kit, mas elas retorna alguns skus com alfanumérico, poderia confirmar se essa view está correta?

 CREATE OR REPLACE FORCE VIEW "OWN_MIS"."VW_DOM_SKU_KIT" ("CD_ITEM_KIT", "CD_ITEM") AS 
  SELECT  ltrim(rtrim(tibom010.t$mitm)) CD_ITEM_KIT,
        ltrim(rtrim(tibom010.t$sitm)) CD_ITEM
FROM    baandb.ttibom010201 tibom010
order by 1;

**Comment by hkasai** [comment]
Filipe,

Falei com o consultor Alexandre Antunes, de suprimentos, e o mesmo me disse que são itens de teste e devem ser desconsiderados.
