### ISSUE TITLE
VW_WMS_TRACKING_PEDIDO_HIST - Campo CD_TRACKING

### ISSUE THREAD

**Issue by rosanaprignolato** [patricknaka/Nova#497]
Humberto,

Conforme conversamos, estamos com informações duplicadas na extração dos dados, porém esse campo vem diferente em todos os registros.

Veja a situação baixo:

![image](https://cloud.githubusercontent.com/assets/7606062/12179044/e8a0755e-b55b-11e5-9b15-5e01b871e7f7.png)

Você poderia analisar?

Obrigada

**Comment by hkasai** [comment]
Rosana,

A tabela 'ORDERSTATUSHISTORY" traz registros do cabeçalho e das linhas da ordem de expedição.
Terá quer filtrar a query para trazer somente o histórico do cabeçalho.

![image](https://cloud.githubusercontent.com/assets/8986936/12217329/2fc9f8ea-b6e4-11e5-90b8-221ab94f4468.png)

![image](https://cloud.githubusercontent.com/assets/8986936/12217350/ac201b7c-b6e4-11e5-8272-da2fa6f5fea9.png)

**Comment by rosanaprignolato** [comment]
Humberto,

incluimos a clausula " where  OSH.ORDERLINENUMBER != ' ' " e agora os dados vieram corretos.
