### ISSUE TITLE
VW_PEV_VALE - Sequencia de entrega nula

### ISSUE THREAD

**Issue by rosanaprignolato** [patricknaka/Nova#499]
Humberto, ao executarmos essa view, pegamos 2 pedidos que não possuem sequencia de entrega: 66047111 e 19437674
Não conseguimos achar esses pedidos nas telas do LN. Seria possível você me ajudar a identificar pq a sequencia de entrega está vindo nula?

**Comment by hkasai** [comment]
Rosana,

Favor desconsiderar os dois vales, pois os respectivos pedidos não existem na cia 201 de homologação.
A sequencia está nula, pois vem da entrega do pedido.

**Comment by rosanaprignolato** [comment]
Ok Humberto, obrigada!
