### ISSUE TITLE
Nova View - VW_PEV_NUM_SERIE

### ISSUE THREAD

**Issue by patricknaka** [patricknaka/Nova#500]
Humberto, boa tarde.

Conforme conversamos precisamos de uma query que retorne o Numero de Série de uma expedição. Neste momento só vamos precisar para os Produtos da Apple fornecedor 623904000173 e 623904000335.

Para cruzar com as nossas PEV estava pensando nas colunas abaixo:

- Numero da OV
- Seq OV
- Numero Entrega
- Codigo do Item
- Numero Série

Poderia avaliar?

![image](https://cloud.githubusercontent.com/assets/7632817/12333985/8cd539c0-bade-11e5-82c6-c68656f4811f.png)

![image](https://cloud.githubusercontent.com/assets/7632817/12334001/9ca0b41a-bade-11e5-853d-48474c92e2a4.png)

**Comment by hkasai** [comment]
Patrick,

A query foi criada no Git. 

Qualquer problema, me avise.

**Comment by patricknaka** [comment]
Rosana, depois consegue montar um processo para extrair essas informações em uma stage para o Eduardo?

**Comment by rosanaprignolato** [comment]
Ok, Patrick. O processo já foi montado e os dados liberados para o Eduardo
