### ISSUE TITLE
VW_GAR_ESTENDIDA - tabela tzncom005201

### ISSUE THREAD

**Issue by rosanaprignolato** [patricknaka/Nova#501]
Humberto,

Essa view está considerando a tabela mencionada como a tabela principal. Precisamos que seja feito um left join com ela, pois segundo o Patrick, esses dados só são gerados uma vez por mês e a nossa carga de garantia será diária e deverá considerar todos os registros.

Obrigada

**Comment by hkasai** [comment]
Rosana,

A query foi alterada e encontra-se no GIT.

**Comment by rosanaprignolato** [comment]
Humberto, já carregamos os dados e qualquer outro problema abriremos um outro chamado.
