### ISSUE TITLE
VW_NFR_CAB

### ISSUE THREAD

**Issue by patricknaka** [patricknaka/Nova#502]
Rosana,

Conseguimos adicionar na nossa ods de NFR as colunas abaixo:

![image](https://cloud.githubusercontent.com/assets/7632817/12590965/b19c9ce0-c44c-11e5-98b9-464b222bd6a2.png)

abs, Patrick Nakazone

**Comment by rosanaprignolato** [comment]
Patrick, o campo foi incluído e a carga realizada. Por favor, verifique se está ok.

**Comment by patricknaka** [comment]
concluido
